### ISSUE TITLE
Update fonts

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-dev#21]
When we get to work on font support tools, we check which fonts require regeneration, e.g., due to newer releases

* [Latin Modern](https://github.com/mathjax/MathJax/issues/1667), 
* [STIX 2.0](https://sourceforge.net/projects/stixfonts/files/Current%20Release/)
* Regenerate the MathJax TeX fonts (e.g., blacker value, tracing of space characters)

**Comment by flying-sheep** [comment]
In short: Your “Latin Modern MathJax” is supposed to be a renamed “Latin Modern Math” (converted to WOFF). It has two bugs:

* The line height metrics are far too high since the font’s OS/2 table is broken

	This one is fixed in the [1.959 upstream release](http://www.gust.org.pl/gustnews/news02-05-10-2014en)

* For all intents and purposes you *don’t* rename it as intened:

	This one is because you don’t change the font’s name [in the “Preferred Family” field](https://cloud.githubusercontent.com/assets/291575/20542517/29ad196a-b102-11e6-9113-e09b65a21082.png).

	```console
	$ fc-match 'Latin Modern Math'
	LatinModernMathJax_Alphabets-Regular.woff: "Latin Modern Math" "Regular"
	```

To circumvent this bug on Arch, you have to add the following to your fontconfig:

```
<fontconfig>
 ...
 <selectfont>
  <rejectfont>
   ...
   <glob>/usr/share/fonts/mathjax*/HTML-CSS/Latin-Modern/woff/*</glob>
  </rejectfont>
 </selectfont>
 ...
</fontconfig>
```

**Comment by flying-sheep** [comment]
Hi! Did you get around to this for MathJax 3?

**Comment by dpvc** [comment]
@flying-sheep, the font update for v3 is still in the future.  Currently v3, only uses the MathJax TeX font, but the infrastructure is in place for better font support, but the code to create the needed data for any given font is not yet in place (the MathJax TeX data was created from the existing data in an *ad hoc* fashion).  So this is still one of the big pieces yet to be created for v3, and it is high on the list for development in the coming year.

**Comment by flying-sheep** [comment]
Thank you for the clarification! Good to know this will be fixed eventually.

**Comment by lilydjwg** [comment]
Years have passed and the font in mathjax is still the ones that cause issues for Firefox...

**Comment by dpvc** [comment]
@lilydjwg, yes, the version 3 font update has taken longer than expected.  I have been working on the font toolchain for several months, now, and will be making a release at the end go August that includes some updates.
